### ISSUE TITLE
global_password doesnt work

### ISSUE THREAD

**Issue by CoinK0in** [unverbuggt/mkdocs-encryptcontent-plugin#39]
I am running into an issue where only my index.md and random page accepts the global_password
        All other pages say invalid password where I dont have set anything in any of the pages, not sure what I am missing here, using CTRL+ENTER to enter global password also doesnt work

_Originally posted by @zerenxyz in https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/issues/37#issuecomment-1273653578_

**Comment by CoinK0in** [comment]
Can you provide more information about your configuration so that I can reproduce your problem?

**Comment by zerenxyz** [comment]
I am using mkdocs-material, I added encryptcontent to plugins like so:
```
plugins:
  - search:
      lang: en
  - tags
  - blog
  ```

This is also my nav setup:
![image](https://user-images.githubusercontent.com/52886201/194938262-32f609d4-266b-482e-a9b8-7c9d0f964dbc.png)

**Comment by CoinK0in** [comment]
The problem seems to be related to the "blog" mode of the insider version of material. 
Did you install the "insider" version of material with the "mkdocs-material-insiders" package ?

**Comment by zerenxyz** [comment]
Yup, I used the insiders package of mkdocs material

**Comment by unverbuggt** [comment]
see [here](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/issues/38#issuecomment-1289550334)
