### ISSUE TITLE
This is not a, issue :) 

### ISSUE THREAD

**Issue by CoinK0in** [unverbuggt/mkdocs-encryptcontent-plugin#53]
I just wanted to send u a simple message, **THANK YOU**.

Over than a year later you continue to develop, improve and correct this project.
I really like what you're doing, the new functions, working on the old ones. 
It's a pleasure to see what this project has become and I'm very happy to have found the right person to pass it on to.
So just thank you for keeping this going. The community also seems to appreciate the efforts you are making for this project.

I will continue and continue to use it.
I hope you continue to do what you do, continue to be as motivated.

**Comment by unverbuggt** [comment]
Thank you for the kind words. It was some good luck, that I could continue what you started. 
I still think this plugin is a hell of a good idea: Being able to upload a website, that not even your hosting provider could know the content of.

I got some ideas on new features to implement, but want to focus on bug fixing the current version right now.
