### ISSUE TITLE
How to change the prompt words of the search box to Chinese

### ISSUE THREAD

**Issue by W1ndys** [unverbuggt/mkdocs-encryptcontent-plugin#68]
I searched for information, and one of the methods was to write "lang: zh" in the configuration parameters of the search plug-in, but I didn't get any correct results. After asking ChatGPT, the method he gave was to directly modify the site-package template. file, but this is too intrusive and not conducive to my deployment in Netlify, so I'm wondering if there is any other non-intrusive solution

**Comment by W1ndys** [comment]
such  as
![image](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/assets/109416673/5090694e-1232-4965-8fb5-67626aa8f503)
![image](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/assets/109416673/2af67b34-bc36-4239-b913-40ef779dc886)

**Comment by unverbuggt** [comment]
Please only post issues related to mkdocs-encryptcontent.

Find information about mkdocs-material here: https://squidfunk.github.io/mkdocs-material/

**Comment by W1ndys** [comment]
> Please only post issues related to mkdocs-encryptcontent.
> 
> Find information about mkdocs-material here: https://squidfunk.github.io/mkdocs-material/

Sorry, I misread the project address. I'm very sorry, I will find the correct project address to submit an issue
