### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by GreggGreen** [unverbuggt/mkdocs-encryptcontent-plugin#73]
<img width="1479" alt="Screenshot 2024-10-13 at 2 32 48 PM" src="https://github.com/user-attachments/assets/f41f7500-6788-4a32-bf41-956d0f1b5412">

**Comment by unverbuggt** [comment]
Please provide some background information and a test configuration

**Comment by GreggGreen** [comment]
I don't know what exactly fixed it but it's working now so we can close this. Thanks
